Neos:
  Media:
    thumbnailGenerators:
      'Ttree\FilePreviews\Domain\Model\ThumbnailGenerator\FilePreviewsThumbnailGenerator':
        apiKey: 'api-key'
        apiSecret: 'api-secret'
        maximumWaitingTime: 30
        maximumFileSize: 2000000
        defaultOptions:
          format: 'jpg'
        retryInterval: 1
        supportedExtensions: [ 'doc', 'docx', 'ppt', 'pptx', 'xls', 'xlxs', 'odt', 'ott', 'odp', 'txt', 'rtf', 'eps' ]
